---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

bird<- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-18/bird_counts.csv") %>% separate(species_latin, c("genus_latin", "species_latin"))

View(bird)
bird %>% count(species_latin) %>% View()
# use stringr  to seperate latin names

bird %>% count(genus_latin,sort=T)
bird %>% count(species_latin, sort =T)
```


```{r}

bird %>% ggplot(aes(how_many_counted_by_hour)) + geom_histogram() + scale_x_log10(labels= scales::comma)





bird %>% ggplot(aes(x = fct_lump(genus_latin,7) , y=how_many_counted_by_hour)) + geom_boxplot()

bird %>% mutate(genus_latin = fct_lump(genus_latin,7)) %>% 
  ggplot(aes(x = fct_reorder(genus_latin, how_many_counted_by_hour) , y=how_many_counted_by_hour)) + geom_boxplot() + coord_flip() + scale_y_log10(labels= scales::comma)

```


```{r}
bird %>% group_by(year) %>% summarise(mean(how_many_counted_by_hour))

bird %>% group_by(year) %>%  tally(how_many_counted_by_hour) %>% ggplot(aes(x=year, y = n, color =   )) + geom_line()



bird %>% group_by(year) %>% mutate(avg_count = mean(how_many_counted_by_hour),
                                   n= n()) %>% ggplot(aes(avg_count, y=n())) + geom_line()
```

maybe look at change over time for various species/genus


```{r}
bird %>% filter(is.na(how_many_counted))
bird %>% group_by(genus_latin) %>% mutate(
  total_year =sum( how_many_counted)) %>% filter(year  %in% c(1921, 2017)) %>% ggplot(aes(x=year, y= total_year)) + geom_point() + coord_flip() + geom_segment( aes(x=year, xend=year, y=0, yend=total_year))

bird %>% group_by(genus_latin) %>% mutate(
  total_year =sum( how_many_counted))  %>% ggplot(aes(x=year, y= total_year, color=genus_latin)) + geom_point() + coord_flip() 


```
think about using something like this

grepl

 bird %>%
+     mutate(type=ifelse(grepl('Owl', species), 'Owl', ifelse(grepl('Duck', species), "Duck", 'Other Species')),
+            count_k=how_many_counted/1000)
