---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
meteorites <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-11/meteorites.csv")

glimpse(meteorites)
meteorites %>% count(id, sort=T)
```


```{r}
library(scales)
meteorites %>% mutate(class = fct_lump(class, 10)) %>% 
  ggplot(aes(x=class, y = mass)) + geom_boxplot() + coord_flip()

meteorites %>% ggplot(aes(mass)) + geom_histogram() + scale_x_log10(labels = comma)

```

things to do:
maybe figure out where they land based on the lat,long data?


```{r}
library(maps)
meteorites$Country <- map.where(database="world", y= as.integer(meteorites$long), x= as.integer( meteorites$lat))


map.where("world", 69.1, 172.6)

```
above doesn;t seem to work for most of the data i have

```{r}
install.packages("revgeo")
library('revgeo')
revgeo(longitude=-86.46222, latitude=33.94954, provider=NULL, API=NULL, output='hash', item='country')


revgeo(longitude=69.1, latitude=172.6, provider=NULL, API=NULL, output='hash', item='country')

met1 <- meteorites[1:50,]

cities <- revgeo(met1$long, met1$lat, provider =  'photon', output = 'frame')

location <- revgeo(meteorites$long, meteorites$lat, provider =  'photon', output = 'frame')

#maybe i should have filtered out the NAs!!!!!


meteorites_filtered <- meteorites %>% filter(!is.na(lat))
#still really big, maybe just fell! (ie seen)

fell <- meteorites_filtered %>% filter(fall == "Fell")

location <- revgeo(fell$long, fell$lat, provider =  'photon', output = 'frame')

write.csv(location, "tmp.csv")
write.csv(my, "tmp.csv")
my_data <- fell %>% cbind(location)
my_data %>% count(country, sort=T)

write.csv(my_data, "joined.csv")
```




```{r}
my_data <- read_


```

maps

```{r}
meteorites_filtered %>% ggplot(aes(long, lat)) + geom_point()

#try

meteorites_filtered %>% ggplot(aes(long, lat)) + borders("world") + geom_point()

my_data %>% ggplot(aes(long, lat, color=country)) + borders("world") + geom_point() + theme(legend.position = "none")


my_data %>% filter(country != "Country Not Found" )%>% ggplot(aes(long, lat, color=country)) + borders("world") + geom_point() + theme(legend.position = "none")

library(gganimate)

my_data %>%  ggplot(aes(long, lat, color=country)) + borders("world") + geom_point() + theme(legend.position = "none") +
transition_states(year, 
                          transition_length = 1, 
                          state_length = 1) + shadow_mark(past=TRUE) +  labs(title = "{closest_state}")


my_data %>% count(year) %>% View()

library(ggridges)

my_data %>% mutate(class = fct_lump(class, 7) ) %>%  ggplot(aes(x= mass, y = class)) + geom_density_ridges() + scale_x_log10(label = scales::comma)
```






```{r}
library(sp)
library(rworldmap)

# The single argument to this function, points, is a data.frame in which:
#   - column 1 contains the longitude in degrees
#   - column 2 contains the latitude in degrees
coords2country = function(points)
{  
  countriesSP <- getMap(resolution='low')
  #countriesSP <- getMap(resolution='high') #you could use high res map from rworldxtra if you were concerned about detail

  # convert our list of points to a SpatialPoints object

  # pointsSP = SpatialPoints(points, proj4string=CRS(" +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"))

  #setting CRS directly to that from rworldmap
  pointsSP = SpatialPoints(points, proj4string=CRS(proj4string(countriesSP)))  


  # use 'over' to get indices of the Polygons object containing each point 
  indices = over(pointsSP, countriesSP)

  # return the ADMIN names of each country
  indices$ADMIN  
  #indices$ISO3 # returns the ISO3 code 
  #indices$continent   # returns the continent (6 continent model)
  #indices$REGION   # returns the continent (7 continent model)
}
```



```{r}
library(leaflet)

leaflet() %>% addCircleMarkers(data = meteorites)

install.packages("rworldmap")
library(rworldmap)
newmap <- getMap()
plot(newmap)
points(meteorites$long, meteorites$lat, col = "blue", cex=.5)
```




