---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lubridate)

video_games_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-30/video_games.csv")

video_games_raw %>% mutate(release_date = mdy(release_date)) %>% filter(is.na(release_date)) %>% View()

video_games_raw %>% filter(number == 484) %>% View()
#note that Hazard Ops is wrong format

vg <- video_games_raw %>% mutate(release_date2 = mdy(release_date))
vg %>% filter(game == "Hazard Ops") %>% mutate(release_date2 = dmy(release_date))


vg %>% count(weekday = wday(release_date2, label = T)) %>% filter(!is.na(weekday)) %>% ggplot(aes(x=weekday, y = n)) + geom_line(group=1)

vg %>% count(weekday = wday(release_date2, label = T)) %>% filter(!is.na(weekday)) %>% ggplot(aes(x=weekday, y = n)) + geom_line(group=1)


vg %>% count(month = month(release_date2, label = T)) %>% filter(!is.na(month)) %>% ggplot(aes(x=month, y = n)) + geom_line(group=1)
```

does price affect sale

```{r}
vg %>% ggplot(aes(x=owners, y = price)) + geom_point()

vg %>% ggplot(aes(x=owners, y = price)) + geom_boxplot() + coord_flip() + scale_y_log10()


#odd since the way owmers is stored
#edit to take min
vg %>% separate(owners, c('min_owner', 'max_owner'), sep= "\\.")  

vg %>% str_split_fixed(owners, " .. ")

pangram <- "The quick brown fox jumps over the lazy dog"

strsplit(vg$owners, " ") 

library(stringr)

vg$owners1 <- word(vg$owners, 1)


vg <- vg %>% mutate(max_owners = str_trim(word(owners, 2, sep = "\\.."))) %>% mutate(min_owners = str_trim(word(owners, 1, sep = "\\.."))) 

              
vg %>% mutate(min_owners = as.numeric(str_replace_all(min_owners, ",", "")))


%>% View()

vg %>% ggplot(aes(x=price, y = min_owners)) + geom_point() +  scale_y_log10()


vg %>% ggplot(aes(x=owners, y = price)) + geom_boxplot() + coord_flip() + scale_y_log10()

              
              
vg %>% ggplot(aes(x=price, y = average_playtime)) + geom_point() + scale_x_log10() + scale_y_log10()
```


lets try again 
```{r}

vg1 <- vg %>% mutate(max_owners = str_trim(word(owners, 2, sep = "\\..")),
         max_owners = as.numeric(str_replace_all(max_owners, ",", "")),
         min_owners = str_trim(word(owners, 1, sep = "\\..")),
         min_owners = as.numeric(str_replace_all(min_owners, ",", ""))) 


vg1 %>% filter(min_owners > 0) %>% ggplot(aes(x=price, y = min_owners)) + geom_point() +  scale_x_log10()  + scale_y_log10()

```



